Add param of withBindVolumn for EtcdClusterExtension
etcd-io/jetcd pull request #1092
Opened 2022-09-17 09:46 UTC by liangyuanpeng

I use remote docker for testcontainer to run unit test and i just got the error:

```
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"invalid volume specification: 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\jetcd_test_etcd0_8631704060335352785:/data.etcd:rw,z'"}
```  

So i add param of bindVolumn for this case that do not need volumn.

2022-09-18 09:20 UTC, lburgazzoli commented
It would be nice to understand why the volume mount fails, ideally his should not be something you should be able to disable as it may be required by the jetcd container

2022-09-25 13:46 UTC, liangyuanpeng commented
> It would be nice to understand why the volume mount fails,

Run unit test on windows, and use remote docker container from linux, the voulme is `C:\\Users\\Administrator\\xxx:/data.etcd:rw,z`, this format can not use by docker container. So just got the error when container start.

>  ideally this should not be something you should be able to disable as it may be required by the jetcd container
Absolutely right, so still create volum for etcd test container by default,  User need to use `withBindVolumn(false)` for disable volumn when they want to this.

2022-09-25 20:49 UTC, lburgazzoli requested changes
some minor changes are needed

2022-09-25 20:49 UTC, lburgazzoli commented on jetcd-launcher/src/main/java/io/etcd/jetcd/launcher/Etcd.java
> +        private boolean bindVolumn = true;
- the default value is usually set in the constructor
- maybe use a better name that describe the intention i.e. bindDataDirectory

2022-09-25 20:49 UTC, lburgazzoli commented on jetcd-launcher/src/main/java/io/etcd/jetcd/launcher/EtcdContainer.java
> +        if(bindVolumn) {
this check may not be needed as if the data directory os null, then the method won't do anything

2022-09-25 20:49 UTC, lburgazzoli commented on jetcd-launcher/src/main/java/io/etcd/jetcd/launcher/EtcdContainer.java
> +        this.bindVolumn=bindVolumn;
probably a checkstyle violation, please reformat the code

2022-09-25 20:49 UTC, lburgazzoli commented on jetcd-launcher/src/main/java/io/etcd/jetcd/launcher/EtcdClusterImpl.java
> +                        .withBindVolumn(bindVolumn)
must be formatted

2022-11-25 06:56 UTC, lburgazzoli commented
@liangyuanpeng can you fix the findings ?

2023-01-29 17:32 UTC, IlyasYOY commented
@lburgazzoli is this PR up to date? 

I opened a #1123, I guess they are almost identical. 

I have all code formatter + tests there. This feature is very important to me. 

Thanks!

2023-01-30 06:54 UTC, lburgazzoli commented
> @lburgazzoli is this PR up to date?
> 
> I opened a #1123, I guess they are almost identical.
> 
> I have all code formatter + tests there. This feature is very important to me.
> 
> Thanks!

Merged, THX !

2023-01-30 06:55 UTC, lburgazzoli commented
Done in https://github.com/etcd-io/jetcd/pull/1123

2023-01-30 06:55 UTC, closed without merging